server {
    listen 80;
    listen [::]:80;
    server_name mail.vprod.nl;
    server_tokens off;
    access_log off;
    location ^~ /.well-known/acme-challenge/ {
        root /var/lib/letsencrypt;
        default_type text/plain;
        try_files $uri =404;
    }
    location / { return 301 https://vprod.nl$request_uri; }
}
